const DAY=86400000;
const round2=x=>Math.round((x+Number.EPSILON)*100)/100;
const isoDate=d=>new Date(d).toISOString().slice(0,10);
function date(v,label='date'){const d=v instanceof Date?new Date(v):new Date(`${v}T00:00:00Z`);if(Number.isNaN(d.getTime()))throw new Error(`Invalid ${label}.`);return d;}
export const LEGAL_INTEREST=[
[2007,6],[2008,7],[2009,5.5],[2010,3.25],[2011,3.75],[2012,4.25],[2013,2.75],[2014,2.75],[2015,2.5],[2016,2.25],[2017,2],[2018,2],[2019,2],[2020,1.75],[2021,1.75],[2022,1.5],[2023,5.25],[2024,5.75],[2025,4.5],[2026,4.5]
].map(([year,rate])=>({from:`${year}-01-01`,to:`${year}-12-31`,rate}));
export const COMMERCIAL_INTEREST=[
['2023-01-01','2023-06-30',10.5],['2023-07-01','2023-12-31',12],['2024-01-01','2024-06-30',12.5],['2024-07-01','2024-12-31',12.5],['2025-01-01','2025-06-30',11.5],['2025-07-01','2025-12-31',10.5],['2026-01-01','2026-06-30',10.5],['2026-07-01','2026-12-31',10.5]
].map(([from,to,rate])=>({from,to,rate}));
function interestSegments(table,start,end,principal){const a=date(start),b=date(end);if(b<a)throw new Error('End date cannot be before start date.');const segments=[];let total=0;for(const row of table){const rf=date(row.from),rt=date(row.to);const s=new Date(Math.max(a,rf)),e=new Date(Math.min(b,rt));if(e<s)continue;const days=Math.floor((e-s)/DAY)+1,interest=principal*(row.rate/100)*(days/365);segments.push({from:isoDate(s),to:isoDate(e),days,rate:row.rate,interest:round2(interest)});total+=interest;}return {segments,total:round2(total)};}
export function statutoryInterestBelgium({principal,start,end,type='legal'}={}){const p=+principal;if(!(p>=0))throw new Error('Principal must be non-negative.');return {principal:p,type,...interestSegments(type==='commercial'?COMMERCIAL_INTEREST:LEGAL_INTEREST,start,end,p)};}

export function easterSunday(year){const a=year%19,b=Math.floor(year/100),c=year%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),month=Math.floor((h+l-7*m+114)/31),day=((h+l-7*m+114)%31)+1;return new Date(Date.UTC(year,month-1,day));}
export function belgianPublicHolidays(year){const e=easterSunday(year),plus=n=>isoDate(new Date(e.getTime()+n*DAY));return [{name:"New Year's Day",date:`${year}-01-01`},{name:'Easter Monday',date:plus(1)},{name:'Labour Day',date:`${year}-05-01`},{name:'Ascension',date:plus(39)},{name:'Whit Monday',date:plus(50)},{name:'National Day',date:`${year}-07-21`},{name:'Assumption',date:`${year}-08-15`},{name:"All Saints' Day",date:`${year}-11-01`},{name:'Armistice',date:`${year}-11-11`},{name:'Christmas',date:`${year}-12-25`}];}
export function workingDaysBetweenBelgium({start,end,includeStart=true,includeEnd=true,customDaysOff=[]}={}){let a=date(start),b=date(end);if(b<a)throw new Error('End date cannot be before start date.');const years=new Set();for(let y=a.getUTCFullYear();y<=b.getUTCFullYear();y++)years.add(y);const holidays=new Map([...years].flatMap(y=>belgianPublicHolidays(y)).map(x=>[x.date,x.name]));for(const x of customDaysOff){const d=String(x).trim();if(/^\d{4}-\d{2}-\d{2}$/.test(d))holidays.set(d,'Custom/substitute day off');}
 let workdays=0,weekend=0,holiday=0,days=[];for(let t=a.getTime();t<=b.getTime();t+=DAY){const d=new Date(t),key=isoDate(d);if((!includeStart&&t===a.getTime())||(!includeEnd&&t===b.getTime()))continue;const dow=d.getUTCDay();let kind='workday',name='';if(dow===0||dow===6){weekend++;kind='weekend';}else if(holidays.has(key)){holiday++;kind='holiday';name=holidays.get(key);}else workdays++;days.push({date:key,kind,name});}return {workdays,weekendDays:weekend,holidayWeekdays:holiday,totalCounted:days.length,days};}
export function addWorkingDaysBelgium({start,days,customDaysOff=[]}={}){const n=+days;if(!Number.isInteger(n))throw new Error('days must be an integer');let d=date(start),left=Math.abs(n),step=n>=0?1:-1;const custom=new Set(customDaysOff.map(String));while(left){d=new Date(d.getTime()+step*DAY);const key=isoDate(d),dow=d.getUTCDay(),holiday=belgianPublicHolidays(d.getUTCFullYear()).some(x=>x.date===key)||custom.has(key);if(dow!==0&&dow!==6&&!holiday)left--;}return isoDate(d);}
