const dec=new TextDecoder();
const u16=(b,p)=>b[p]|(b[p+1]<<8);
const u32=(b,p)=>(b[p]|(b[p+1]<<8)|(b[p+2]<<16)|(b[p+3]<<24))>>>0;
const unesc=s=>String(s??'').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&');
async function inflateRaw(bytes){if(typeof DecompressionStream==='undefined')throw new Error('This browser cannot open compressed XLSX files; save the conversion table as CSV instead.');const ds=new DecompressionStream('deflate-raw');return new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(ds)).arrayBuffer());}
async function zipEntries(bytes){bytes=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes);let e=-1;for(let p=bytes.length-22;p>=Math.max(0,bytes.length-65557);p--)if(u32(bytes,p)===0x06054b50){e=p;break;}if(e<0)throw new Error('Invalid XLSX/ZIP file.');const count=u16(bytes,e+10),cd=u32(bytes,e+16),out=new Map();let p=cd;for(let i=0;i<count;i++){if(u32(bytes,p)!==0x02014b50)throw new Error('Invalid XLSX central directory.');const method=u16(bytes,p+10),comp=u32(bytes,p+20),size=u32(bytes,p+24),nl=u16(bytes,p+28),xl=u16(bytes,p+30),cl=u16(bytes,p+32),local=u32(bytes,p+42),name=dec.decode(bytes.subarray(p+46,p+46+nl)),ln=u16(bytes,local+26),lx=u16(bytes,local+28),start=local+30+ln+lx,packed=bytes.subarray(start,start+comp);const data=method===0?packed.slice():method===8?await inflateRaw(packed):null;if(!data||data.length!==size)throw new Error(`Unsupported XLSX compression for ${name}.`);out.set(name,data);p+=46+nl+xl+cl;}return out;}
function sharedStrings(xml){const out=[];for(const m of xml.matchAll(/<si\b[^>]*>([\s\S]*?)<\/si>/g)){let s='';for(const t of m[1].matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g))s+=unesc(t[1]);out.push(s);}return out;}
const colNo=ref=>{let n=0;for(const ch of String(ref).match(/^[A-Z]+/)?.[0]||'')n=n*26+ch.charCodeAt(0)-64;return n-1;};
function sheetRows(xml,shared){const rows=[];for(const rm of xml.matchAll(/<row\b[^>]*>([\s\S]*?)<\/row>/g)){const row=[];for(const cm of rm[1].matchAll(/<c\b([^>]*)>([\s\S]*?)<\/c>/g)){const attrs=cm[1],body=cm[2],ref=/\br="([A-Z]+\d+)"/.exec(attrs)?.[1]||'',type=/\bt="([^"]+)"/.exec(attrs)?.[1]||'',i=colNo(ref);let v='';if(type==='inlineStr'){for(const t of body.matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g))v+=unesc(t[1]);}else{const raw=/<v>([\s\S]*?)<\/v>/.exec(body)?.[1]??'';v=type==='s'?shared[+raw]??'':unesc(raw);}row[i]=v;}while(row.length&&row.at(-1)===undefined)row.pop();rows.push(row.map(x=>x??''));}return rows;}
export async function parseXlsxTables(bytes){const files=await zipEntries(bytes),shared=files.has('xl/sharedStrings.xml')?sharedStrings(dec.decode(files.get('xl/sharedStrings.xml'))):[];const names=[...files.keys()].filter(x=>/^xl\/worksheets\/sheet\d+\.xml$/.test(x)).sort((a,b)=>+(/sheet(\d+)/.exec(a)?.[1]||0)-+(/sheet(\d+)/.exec(b)?.[1]||0));if(!names.length)throw new Error('No worksheets found in XLSX.');return names.map((name,i)=>({name:`Sheet ${i+1}`,rows:sheetRows(dec.decode(files.get(name)),shared)}));}
const normCode=v=>(String(v??'').match(/\d+/g)||[]).join('');
export function buildNaceMigrationMap(rows){if(!Array.isArray(rows)||!rows.length)throw new Error('Conversion table is empty.');let best=null;for(let r=0;r<Math.min(20,rows.length);r++){const cells=rows[r].map(x=>String(x).toLowerCase());const oldCols=[],newCols=[];cells.forEach((x,i)=>{if(x.includes('2008'))oldCols.push(i);if(x.includes('2025'))newCols.push(i);});if(oldCols.length&&newCols.length){best={headerRow:r,oldCol:oldCols[0],newCol:newCols[0],headers:rows[r]};break;}}if(!best)throw new Error('Could not detect NACE-BEL 2008 and 2025 columns. Save the official table as CSV with headers containing 2008 and 2025, or select a newer official conversion file.');const map=new Map();for(const row of rows.slice(best.headerRow+1)){const old=normCode(row[best.oldCol]),neu=normCode(row[best.newCol]);if(!old||!neu)continue;if(!map.has(old))map.set(old,new Set());map.get(old).add(neu);}return {headerRow:best.headerRow,oldColumn:best.headers[best.oldCol],newColumn:best.headers[best.newCol],mappings:Object.fromEntries([...map].map(([k,v])=>[k,[...v]]))};}
export function migrateNaceCodes(codes,mapping){const list=Array.isArray(codes)?codes:String(codes??'').split(/[\s,;]+/);return list.map(raw=>{const old=normCode(raw),matches=mapping?.[old]||[];return {input:String(raw),oldCode:old,newCodes:matches,status:matches.length===1?'one-to-one':matches.length>1?'one-to-many':'not-found'};}).filter(x=>x.oldCode);}
